	.align 2
gTilesetPalOverrides_General::
	.byte 2
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0
	.4byte gTilesetPalOverride_General02

	.byte 7
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0
	.4byte gTilesetPalOverride_General07

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0
	.4byte NULL

	.align 2
gTilesetPalOverrides_PalletTown::
	.byte 8
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0
	.4byte gTilesetPalOverride_PalletTown08

	.byte 9
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0
	.4byte gTilesetPalOverride_PalletTown09

	.byte 10
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0
	.4byte gTilesetPalOverride_PalletTown10

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0
	.4byte NULL
